Database/3_2/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

Database/3_2/practice1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todos/', include('todos.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

Database/3_2/todos/urls.py
from django.urls import path
from . import views

app_name = 'todos'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:todo_pk>/', views.toggle, name='toggle'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
]

Database/3_2/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

Database/3_2/todos/models.py
from django.db import models
from django.conf import settings


class Todo(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    completed = models.BooleanField(default=False)

Database/3_2/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields

Database/3_2/todos/forms.py
from django import forms
from .models import Todo

class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        exclude = ('author',)

Database/3_2/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserCreationForm


def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
    else:
        form = CustomUserCreationForm()

    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect('todos:index')
    else:
        form = AuthenticationForm()

    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)



def logout(request):
    auth_logout(request)
    return redirect('todos:index')

Database/3_2/todos/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_safe, require_http_methods
from .models import Todo
from .forms import TodoForm


@require_safe
def index(request):
    if not request.user.is_authenticated:
        return redirect('accounts:login')

    # 역참조를 통해 유저 정보 가져오기
    todos = request.user.todo_set.all()
    context = {
        'todos': todos,
    }
    return render(request, 'todos/index.html', context)


@require_http_methods(['GET', 'POST'])
def create(request):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    
    if request.method == "POST":
        form = TodoForm(request.POST)
        if form.is_valid():
            todo = form.save(commit=False)
            todo.author = request.user
            form.save()
            return redirect('todos:index')
    else:
        form = TodoForm()
    
    context = {
        'form': form,
    }
    return render(request, 'todos/create.html', context)


def toggle(request, todo_pk):
    if not request.user.is_authenticated:
        return redirect('accounts:login')

    todo = Todo.objects.get(pk=todo_pk)
    
    if request.user == todo.author:
        todo.completed = not todo.completed
        todo.save()
    return redirect('todos:index')


def delete(request, article_pk):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    
    todo = Todo.objects.get(pk=article_pk)
    if request.user == todo.auther:
        todo.delete()
    return redirect('todos:index')

Database/3_2/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Todos</title>
</head>
<body>
  <div class="container">
   {% if request.user.is_authenticated %}
     <a href="{% url 'todos:create' %}">NEW</a>
     <a href="{% url 'accounts:logout' %}">logout</a>
   {% else %}
     <a href="{% url 'accounts:login' %}">login</a>
     <a href="{% url 'accounts:signup' %}">signup</a>
   {% endif %}
  {% block content %}
  
  {% endblock content %}
  </div>
</body>
</html>

Database/3_2/todos/templates/todos/create.html
{% extends 'base.html' %}
{% block content %}
  <h2>Create</h2>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Create</button>
  </form>
{% endblock %}

Database/3_2/todos/templates/todos/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Todo</h1>
<hr>
<ul>
  {% for todo in todos %}
    <li>{{ todo.author }} - {{ todo.title }}</li>
    {% if request.user == todo.author %}
      <form action="{% url "todos:toggle" todo.pk %}" method="POST">
        {% csrf_token %}
        {% if todo.completed %}
          <button>취소하기</button>
        {% else %}
          <button>완료하기</button>
        {% endif %}
      </form>
      <form action="{% url "todos:delete" todo.pk %}" method="POST">
        {% csrf_token %}
        <button>삭제하기</button>
      </form>
    {% endif %}
  {% empty %}
    <p>작성된 글이 없습니다.</p>
  {% endfor %}
</ul>
{% endblock content %}